### ISSUE TITLE
一直提示无效host

### ISSUE THREAD

**Issue by clhaaaa** [Talaxy009/mirai-http-webhook#1]
报错：
Failed @ auth: Invalid host
可是我config里面设置的http://127.0.0.1:8080 完全可以访问
<img width="435" alt="image" src="https://user-images.githubusercontent.com/13366961/125161065-b6aab080-e1b2-11eb-91b0-5d16dd17c845.png">
<img width="345" alt="image" src="https://user-images.githubusercontent.com/13366961/125161074-c924ea00-e1b2-11eb-9bfe-23e16c6340f8.png">

**Comment by Talaxy009** [comment]
mirai-api-http 从 2.0 开始[变更了认证流程](https://github.com/project-mirai/mirai-api-http/releases/tag/v2.0-RC1)，本项目使用的 [node-mirai](https://github.com/RedBeanN/node-mirai) 没有对 2.0 的 mirai-api-http 进行适配，应该是这个原因导致了认证失败，可以尝试使用 [1.12.0](https://github.com/project-mirai/mirai-api-http/releases/tag/v1.12.0) 的 mirai-api-http，其适配了 2.7-M1 的 mirai

**Comment by clhaaaa** [comment]
明白了，感谢

**Comment by clhaaaa** [comment]
还有一个问题，我对监听的端口使用形如{"token":"xxxxxx","text":"test1"}这样的json post请求，得到的响应却是{err: 1, msg: "token"}，确定token没有问题……那么请求是哪里不对呢？

**Comment by Talaxy009** [comment]
嗯，这个的话目前只实现了对 get 请求的响应

**Comment by clhaaaa** [comment]
> 嗯，这个的话目前只实现了对 get 请求的响应

那有没有请求的范例……

**Comment by Talaxy009** [comment]
稍后会更新文档的，这是一个请求范例：http://host:port?token=abcd&text=测试&image=https://bkimg.cdn.bcebos.com/pic/6609c93d70cf3bc79f3ded3c434bada1cd11738bfc82

**Comment by clhaaaa** [comment]
嗯嗯我已经搞定了 我在改post的了

**Comment by Talaxy009** [comment]
好的，我已经把文档推送上来了，如果需要的话
